### ISSUE TITLE
dosfstools: url

### ISSUE THREAD

**Issue by krisklau** [LSTS/glued#19]
The download URL needs to be updated.  http://daniel-baumann.ch/files/software/dosfstools/dosfstools-3.0.20.tar.gz is no longer available. New url should point to arrchive from here: https://github.com/dosfstools/dosfstools/releases/tag/v3.0.20

**Comment by josebraga** [comment]
Thanks,
stored in our server, http://www.lsts.pt/glued/dosfstools-3.0.20.tar.gz
