### ISSUE TITLE
Glued does not start

### ISSUE THREAD

**Issue by aljimgar** [LSTS/glued#21]
Hi, 

I have compiled the Raspberry Pi and Noptilus-3 versions without problems, but when I try to run them from the sd memory, nothing happens, the screen remains black. ¿How could I solve this problem?

Best

**Comment by rasmartins** [comment]
Hi,

GLUED is meant to be used in autonomous systems. The console is available on the Raspberry Pi 2 UART and HDMI is not used.

**Comment by aljimgar** [comment]
¿On other versions of the Raspberry Pi works?

**Comment by rasmartins** [comment]
GLUED only supports the Raspberry Pi 2
