### ISSUE TITLE
Linux 3.14 EOL

### ISSUE THREAD

**Issue by krisklau** [LSTS/glued#31]
Hi,

As 3.14 reached end-of-life, is an upgrade to 4.4 (or 4.9, recently announced LTS) in the plans?

Best regards,
Kristian

**Comment by tsmarques** [comment]
Hi krisklau,

there are plans to upgrade to 4.4, at least. We're working on it.

Regards,
tsm

**Comment by krisklau** [comment]
Thanks! I'm working on some new drivers at this end, so I'll base these on 4.4 then. (rather than 4.9)

KK

**Comment by krisklau** [comment]
Hi,

Any updates on this? I saw that there was a reverted commit earlier that upgraded to 4.4. Could you elaborate on what issues you saw that prevented this upgrade at that time?

Thanks,
Kristian

**Comment by tsmarques** [comment]
Hi, sorry for the delay.

regarding the revert I'm not sure, perhaps it was a first test made by @pmfg, he is handling the update. You can check its progress at [feature/linux-update](https://github.com/LSTS/glued/tree/feature/linux-update). From the tests I made everything seems fine and if all goes well it won't take much to merge it into master. If you already have some drivers perhaps you could test them against that branch and give us any feedback?

Thanks,
tsm

**Comment by tsmarques** [comment]
merged into master @https://github.com/LSTS/glued/commit/200dfc2205817ebf883c02ba1d7f65ab606e4d5d

Any problems, please report.
tsm

**Comment by krisklau** [comment]
Thanks!
